"""
IPO Intelligence ML Service
FastAPI microservice for IPO listing outcome prediction using XGBoost.
"""

import os
import sys
import numpy as np
from pathlib import Path
from typing import Optional
from fastapi import FastAPI, HTTPException, Header
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

# Add model directory to path
sys.path.insert(0, str(Path(__file__).parent))
from model.train import (
    train_model, load_model, build_feature_vector,
    LABEL_ORDER, MODEL_PATH
)

app = FastAPI(
    title="IPO Intelligence ML Service",
    version="1.0.0",
    description="AI-powered IPO listing outcome prediction. For educational purposes only.",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

DISCLAIMER = (
    "This prediction is generated by an AI model for informational and educational purposes only. "
    "It does NOT constitute investment advice. Past performance of IPOs does not guarantee future results. "
    "GMP data is from unofficial grey markets and is not regulated by SEBI. "
    "Please consult a SEBI-registered investment advisor before making any investment decision."
)

MODEL_VERSION = "1.0.0"

# Label score midpoints for weighted scoring
LABEL_SCORE_MAP = {
    "STRONG_CAUTION": 12.5,
    "CAUTIOUS": 37.5,
    "NEUTRAL": 52.5,
    "POSITIVE": 67.5,
    "STRONG_POSITIVE": 87.5,
}


def score_to_label(score: float) -> str:
    if score >= 75:
        return "STRONG_POSITIVE"
    elif score >= 60:
        return "POSITIVE"
    elif score >= 45:
        return "NEUTRAL"
    elif score >= 30:
        return "CAUTIOUS"
    else:
        return "STRONG_CAUTION"


def compute_signals(features: dict, proba: list, classes: list) -> dict:
    """Break down prediction into interpretable signal scores (0-100)."""
    gmp = features.get("gmp_percent", 0)
    qib = features.get("qib_times", 0)
    total = features.get("total_times", 0)
    vix = features.get("vix_current", 15)
    nifty = features.get("nifty_change_1w", 0)
    pe = features.get("pe_ratio", 0)
    promoter = features.get("promoter_holding_pct", 0)

    # Simple heuristic signal scores
    gmp_signal = min(100, max(0, 50 + gmp * 3))  # +3 points per 1% GMP
    sub_signal = min(100, max(0, min(qib / 2, 50) + min(total / 3, 50)))  # QIB + total
    market_signal = min(100, max(0, 50 + nifty * 5 + (20 - vix) * 1.5))
    fundamental_signal = min(100, max(0, 40 + (promoter - 50) * 0.5 + (30 - pe) * 0.3 if pe > 0 else 50))
    sector_signal = float(np.mean(proba) * 100)

    return {
        "gmp": round(gmp_signal, 1),
        "subscription": round(sub_signal, 1),
        "market": round(market_signal, 1),
        "fundamentals": round(fundamental_signal, 1),
        "sector": round(sector_signal, 1),
    }


class PredictRequest(BaseModel):
    ipo_name: str
    sector: str = "Other"
    issue_size_cr: float = 0.0
    price_band_high: float = 0.0
    lot_size: int = 0
    gmp_percent: float = 0.0
    qib_times: float = 0.0
    hni_times: float = 0.0
    retail_times: float = 0.0
    total_times: float = 0.0
    nifty_change_1w: float = 0.0
    vix_current: float = 15.0
    pe_ratio: float = 0.0
    promoter_holding_pct: float = 0.0


class PredictResponse(BaseModel):
    score: float
    label: str
    confidence: float
    signals: dict
    features_snapshot: dict
    model_version: str
    disclaimer: str


# Load model on startup (or train if not present)
_model = None
_encoder = None


@app.on_event("startup")
async def startup_event():
    global _model, _encoder
    try:
        _model, _encoder = load_model()
        print(f"[ML Service] Model loaded. Version: {MODEL_VERSION}")
    except Exception as e:
        print(f"[ML Service] Could not load model on startup: {e}")


@app.get("/health")
async def health():
    return {
        "status": "ok",
        "model_loaded": MODEL_PATH.exists(),
        "model_version": MODEL_VERSION,
    }


@app.post("/predict", response_model=PredictResponse)
async def predict(req: PredictRequest):
    global _model, _encoder
    if _model is None:
        try:
            _model, _encoder = load_model()
        except Exception as e:
            raise HTTPException(status_code=503, detail=f"Model not available: {e}")

    features_dict = req.dict()
    feature_vector = build_feature_vector(features_dict)

    proba = _model.predict_proba([feature_vector])[0]
    predicted_class_idx = int(np.argmax(proba))
    confidence = float(proba[predicted_class_idx])

    # Weighted score: sum(prob_i * score_midpoint_i)
    score = sum(
        float(proba[i]) * LABEL_SCORE_MAP.get(_encoder.classes_[i], 50)
        for i in range(len(_encoder.classes_))
    )
    score = round(min(100, max(0, score)), 1)
    label = score_to_label(score)
    signals = compute_signals(features_dict, proba.tolist(), _encoder.classes_.tolist())

    return PredictResponse(
        score=score,
        label=label,
        confidence=round(confidence, 3),
        signals=signals,
        features_snapshot=features_dict,
        model_version=MODEL_VERSION,
        disclaimer=DISCLAIMER,
    )


@app.post("/retrain")
async def retrain(x_api_key: str = Header(...)):
    expected_key = os.environ.get("ML_API_KEY", "change-me-ml-secret")
    if x_api_key != expected_key:
        raise HTTPException(status_code=403, detail="Invalid API key")

    global _model, _encoder
    try:
        _model, _encoder = train_model()
        return {"status": "retrained", "model_version": MODEL_VERSION}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Retrain failed: {e}")
