import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'About — How IPOPredictor Works',
  description: 'Learn how IPOPredictor uses AI and machine learning to predict Indian IPO listing outcomes. Methodology, data sources, and disclaimers.',
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-lg font-bold text-slate-100 mb-4 pb-2 border-b border-slate-800">{title}</h2>
      <div className="space-y-3 text-slate-400 text-sm leading-relaxed">{children}</div>
    </section>
  )
}

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 py-10">
      <div className="mb-8">
        <h1 className="text-3xl font-black text-slate-100 mb-2">About IPOPredictor</h1>
        <p className="text-slate-500">How it works, where the data comes from, and what the AI score means.</p>
      </div>

      {/* Big SEBI disclaimer */}
      <div className="border-2 border-amber-500/40 bg-amber-500/5 rounded-xl px-5 py-4 mb-10">
        <p className="text-amber-400 font-bold text-base mb-2">⚠ Important Legal Disclaimer</p>
        <p className="text-amber-200/80 text-sm leading-relaxed">
          IPOPredictor is an <strong>AI-based educational and informational tool only</strong>. We are
          NOT registered with SEBI as an investment advisor. Nothing on this website constitutes
          investment advice, recommendations to purchase or dispose of securities, or any other
          regulated financial service. Past IPO performance does not guarantee future results.
          All AI scores are algorithmic estimates with significant uncertainty. Please consult a
          SEBI-registered investment advisor before making any investment decision.
        </p>
      </div>

      <Section title="What is IPOPredictor?">
        <p>
          IPOPredictor is a free, public website that automatically tracks all Indian IPOs (both
          Mainboard and SME) listed on NSE and BSE. We collect publicly available data — subscription
          figures, grey market premiums, issue details, and market indices — and feed them into a
          machine learning model to generate an informational score.
        </p>
        <p>
          The site is entirely free. No signup, no paywall, no investment recommendations. Just data
          and AI-generated analysis for educational purposes.
        </p>
      </Section>

      <Section title="How the AI Score Works">
        <p>
          The AI score (0–100) is generated by an XGBoost machine learning model trained on
          historical Indian IPO data from 2019 to 2024. The model looks at a combination of
          signals at the time of the IPO:
        </p>
        <ul className="list-disc pl-5 space-y-1.5">
          <li><strong className="text-slate-300">GMP Signal</strong> — Grey market premium as a % of issue price. A high positive GMP historically correlates with strong listing gains.</li>
          <li><strong className="text-slate-300">Subscription Signal</strong> — QIB (institutional), HNI, and retail subscription multiples. QIB subscription is the strongest predictor.</li>
          <li><strong className="text-slate-300">Market Trend</strong> — Nifty 50 direction and India VIX (fear index). IPOs list better in bullish, low-VIX environments.</li>
          <li><strong className="text-slate-300">Fundamentals</strong> — Issue valuation (P/E ratio), promoter holding %, and issue size.</li>
          <li><strong className="text-slate-300">Sector Trend</strong> — Historical listing performance of IPOs in the same sector.</li>
        </ul>
        <p>
          The model outputs a probability distribution across 5 outcome categories. These are
          weighted to produce a single 0–100 score. The score updates as new data comes in
          (e.g., when GMP changes or subscription data is updated).
        </p>
      </Section>

      <Section title="Score Labels">
        <p>The score maps to one of 5 informational labels (we do NOT use &quot;buy&quot; or &quot;sell&quot;):</p>
        <div className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden mt-2">
          {[
            { range: '75–100', label: 'Strong Positive', color: 'text-emerald-400', desc: 'Model expects strong listing performance' },
            { range: '60–74', label: 'Positive', color: 'text-emerald-300', desc: 'Model expects above-average listing' },
            { range: '45–59', label: 'Neutral', color: 'text-amber-400', desc: 'Model expects neutral outcome' },
            { range: '30–44', label: 'Cautious', color: 'text-orange-400', desc: 'Model indicates caution' },
            { range: '0–29', label: 'Strong Caution', color: 'text-red-400', desc: 'Model signals high risk' },
          ].map((row) => (
            <div key={row.label} className="flex items-center gap-4 px-4 py-2.5 border-b border-slate-800/60 last:border-0">
              <span className="text-slate-500 font-mono text-xs w-14 shrink-0">{row.range}</span>
              <span className={`font-semibold text-sm w-28 shrink-0 ${row.color}`}>{row.label}</span>
              <span className="text-slate-500 text-xs">{row.desc}</span>
            </div>
          ))}
        </div>
      </Section>

      <Section title="Data Sources">
        <div className="space-y-2">
          {[
            { source: 'Chittorgarh.com', type: 'IPO list, dates, price band, lot size', frequency: 'Every 6 hours' },
            { source: 'NSE India / BSE India', type: 'Subscription data (QIB, HNI, Retail)', frequency: 'Every 2 hours (market hours)' },
            { source: 'InvestorGain.com', type: 'Grey Market Premium (GMP)', frequency: 'Every 4 hours' },
            { source: 'NSE India API', type: 'Nifty 50, Bank Nifty, India VIX', frequency: 'Every 1 hour (market hours)' },
            { source: 'NSE / BSE', type: 'Listing prices and day performance', frequency: '10:30am + 4pm on listing dates' },
          ].map((row) => (
            <div key={row.source} className="flex gap-3 bg-slate-900/50 border border-slate-800 rounded-lg px-3 py-2.5">
              <div className="flex-1">
                <p className="text-slate-300 font-medium text-sm">{row.source}</p>
                <p className="text-slate-500 text-xs">{row.type}</p>
              </div>
              <p className="text-slate-600 text-xs shrink-0">{row.frequency}</p>
            </div>
          ))}
        </div>
        <p className="text-amber-400/70 text-xs">
          GMP data from InvestorGain.com is sourced from the unofficial grey market. It is not verified or
          endorsed by any stock exchange or SEBI. Treat it as informal market sentiment only.
        </p>
      </Section>

      <Section title="Model Accuracy">
        <p>
          Model accuracy varies by market conditions and IPO type. During bull markets with strong
          subscription data, the model tends to be more accurate. SME IPOs with limited data
          have higher uncertainty.
        </p>
        <p>
          We retrain the model every week using newly listed IPO results to continuously improve
          predictions. You can see the current model accuracy on the{' '}
          <a href="/performance" className="text-emerald-400 hover:underline">Performance page</a>.
        </p>
        <p>
          Confidence below 50% means the model has limited data and the prediction should be
          treated with extra skepticism (we show a &quot;Low confidence&quot; indicator in these cases).
        </p>
      </Section>

      <Section title="What We Don't Do">
        <ul className="list-disc pl-5 space-y-1.5">
          <li>We do not provide personalised investment advice</li>
          <li>We do not manage money or handle transactions</li>
          <li>We are not registered with SEBI as an investment advisor, analyst, or portfolio manager</li>
          <li>We do not guarantee any returns or accuracy of predictions</li>
          <li>GMP data shown here is purely informational and does not reflect regulated market prices</li>
        </ul>
      </Section>
    </div>
  )
}
